version : "2.1"
services :
    app :
        container_name : notes-app
        restart : always
        build : .
        ports :
            - "4000:4000"
        links :
            - mongo
    mongo :
        container_name : notes-db-app
        image : mongo
        ports :
            - "27017:27017"